const DRILL_POOL = [
  {
    id: 'toe-taps',
    name: 'Toe Taps',
    category: 'footwork',
    type: 'timer',
    duration: 60,
    equipment: [],
    xp: 15,
    description: 'Stand over the ball and tap the top with alternating feet as fast as possible. Keep knees slightly bent, stay light on your toes, and maintain rhythm. Great for touch and coordination.',
  },
  {
    id: 'sole-rolls',
    name: 'Sole Rolls',
    category: 'ball-control',
    type: 'timer',
    duration: 45,
    equipment: ['ball'],
    xp: 20,
    description: 'Roll the ball across your body with the sole of one foot, then pull it back with the other. Keep the ball close and use small, controlled touches.',
  },
  {
    id: 'ladder-in-out',
    name: 'Ladder In-Out',
    category: 'agility',
    type: 'reps',
    reps: 20,
    equipment: ['ladder'],
    xp: 25,
    description: 'Step in and out of each ladder rung with quick feet. Lead with one foot in, then bring the other in, then step out. Alternate lead foot each rep.',
  },
  {
    id: 'cone-weave',
    name: 'Cone Weave',
    category: 'agility',
    type: 'reps',
    reps: 10,
    equipment: ['cones', 'ball'],
    xp: 30,
    description: 'Dribble through cones placed 2 yards apart using the outside of your foot. Cut sharply at each cone and keep your head up between touches.',
  },
  {
    id: 'box-jumps',
    name: 'Quick Feet Box',
    category: 'footwork',
    type: 'timer',
    duration: 30,
    equipment: [],
    xp: 15,
    description: 'Imagine a small box on the ground. Step in with both feet, then out to each side: front, back, left, right. Stay on the balls of your feet throughout.',
  },
  {
    id: 'inside-outside',
    name: 'Inside-Outside Touches',
    category: 'ball-control',
    type: 'timer',
    duration: 60,
    equipment: ['ball'],
    xp: 20,
    description: 'Alternate inside and outside of the same foot to move the ball side to side. Switch feet every 15 seconds. Keep touches small and controlled.',
  },
  {
    id: 'scissors',
    name: 'Scissors',
    category: 'footwork',
    type: 'reps',
    reps: 30,
    equipment: [],
    xp: 15,
    description: 'Circle one foot around the front of the standing leg, then switch. Mimic the scissors move without a ball first, then add a stationary ball between your feet.',
  },
  {
    id: 'lateral-hops',
    name: 'Lateral Hops',
    category: 'agility',
    type: 'timer',
    duration: 45,
    equipment: ['cones'],
    xp: 20,
    description: 'Place two cones 2 feet apart. Hop side to side over an imaginary line between them, landing softly on both feet. Drive with your arms for balance.',
  },
  {
    id: 'pull-push',
    name: 'Pull-Push Dribble',
    category: 'ball-control',
    type: 'reps',
    reps: 40,
    equipment: ['ball'],
    xp: 25,
    description: 'Pull the ball back with the sole, then push it forward with the inside of the same foot. Alternate feet. Keep the ball within arm\'s reach at all times.',
  },
  {
    id: 'tic-tac-toe',
    name: 'Tic-Tac-Toe',
    category: 'footwork',
    type: 'timer',
    duration: 45,
    equipment: ['ball'],
    xp: 20,
    description: 'Tap the ball between your feet using the inside of each foot. The ball should travel in a V-shape. Increase speed as you find your rhythm.',
  },
  {
    id: 'figure-eight',
    name: 'Figure Eight',
    category: 'ball-control',
    type: 'reps',
    reps: 15,
    equipment: ['cones', 'ball'],
    xp: 30,
    description: 'Set two cones 3 yards apart. Dribble around them in a figure-eight pattern using both feet. Cut tight around each cone.',
  },
  {
    id: 'high-knees',
    name: 'High Knees Sprint',
    category: 'agility',
    type: 'timer',
    duration: 30,
    equipment: [],
    xp: 15,
    description: 'Drive knees up to hip height while moving forward or in place. Pump arms vigorously. Focus on quick ground contact.',
  },
  {
    id: 'shuffle-steps',
    name: 'Shuffle Steps',
    category: 'footwork',
    type: 'timer',
    duration: 40,
    equipment: ['cones'],
    xp: 20,
    description: 'Set cones 5 yards apart. Shuffle laterally between them, touching each cone. Stay low in an athletic stance with quick, short steps.',
  },
  {
    id: 'roll-cut',
    name: 'Roll & Cut',
    category: 'ball-control',
    type: 'reps',
    reps: 25,
    equipment: ['ball'],
    xp: 25,
    description: 'Roll the ball with your sole, then take a sharp cut with the outside of the same foot. Alternate directions left and right each rep.',
  },
  {
    id: 'ladder-icky-shuffle',
    name: 'Icky Shuffle',
    category: 'agility',
    type: 'reps',
    reps: 16,
    equipment: ['ladder'],
    xp: 25,
    description: 'Classic ladder drill: in-in-out through each rung. One foot leads in, the other follows, then step out to the side. Stay on your toes.',
  },
  {
    id: 'bell-taps',
    name: 'Bell Taps',
    category: 'footwork',
    type: 'timer',
    duration: 50,
    equipment: ['ball'],
    xp: 20,
    description: 'Tap the ball back and forth between your feet in a bell-shaped arc. Use the inside of each foot and keep your body centered over the ball.',
  },
  {
    id: 'zigzag-dribble',
    name: 'Zigzag Dribble',
    category: 'ball-control',
    type: 'reps',
    reps: 12,
    equipment: ['cones', 'ball'],
    xp: 30,
    description: 'Set 5 cones in a zigzag 2 yards apart. Dribble through using one foot only, then return using the other foot.',
  },
  {
    id: 'single-leg-hop',
    name: 'Single-Leg Hops',
    category: 'agility',
    type: 'reps',
    reps: 20,
    equipment: [],
    xp: 20,
    description: 'Hop forward on one leg for 10 reps, then switch. Land softly with a slight knee bend. Use arms for balance and control.',
  },
  {
    id: 'v-pulls',
    name: 'V-Pulls',
    category: 'footwork',
    type: 'reps',
    reps: 35,
    equipment: ['ball'],
    xp: 20,
    description: 'Pull the ball diagonally back with the sole, forming a V shape, then push forward with the inside. Alternate feet each rep.',
  },
  {
    id: 'ladder-lateral',
    name: 'Lateral Quick Steps',
    category: 'agility',
    type: 'timer',
    duration: 40,
    equipment: ['ladder'],
    xp: 25,
    description: 'Face sideways to the ladder and step both feet into each rung, then out. Move down the ladder quickly without crossing your feet.',
  },
  {
    id: 'cruyff-turn',
    name: 'Cruyff Turn Practice',
    category: 'ball-control',
    type: 'reps',
    reps: 20,
    equipment: ['ball', 'cones'],
    xp: 35,
    description: 'Dribble toward a cone, fake a pass, then drag the ball behind your standing leg with the inside of your foot and turn away.',
  },
  {
    id: 'jump-rope-mimic',
    name: 'Jump Rope Mimic',
    category: 'footwork',
    type: 'timer',
    duration: 60,
    equipment: [],
    xp: 15,
    description: 'Mimic jump rope without a rope. Small hops on the balls of your feet, wrists rotating at your sides. Build cardio and foot speed.',
  },
  {
    id: 'cone-sprint',
    name: 'Cone Sprint & Backpedal',
    category: 'agility',
    type: 'reps',
    reps: 8,
    equipment: ['cones'],
    xp: 25,
    description: 'Sprint to a cone 10 yards away, touch it, then backpedal to start. Stay on the balls of your feet during the backpedal.',
  },
  {
    id: 'drag-back',
    name: 'Drag Backs',
    category: 'ball-control',
    type: 'timer',
    duration: 45,
    equipment: ['ball'],
    xp: 20,
    description: 'Roll the ball back with the sole of one foot while stepping past it, then switch feet. Keep your body between the ball and an imaginary defender.',
  },
];

const CATEGORY_LABELS = {
  footwork: 'Footwork',
  'ball-control': 'Ball Control',
  agility: 'Agility',
};

const FOCUS_AREAS = {
  balanced: { footwork: 0.34, 'ball-control': 0.33, agility: 0.33 },
  footwork: { footwork: 0.6, 'ball-control': 0.2, agility: 0.2 },
  'ball-control': { footwork: 0.2, 'ball-control': 0.6, agility: 0.2 },
  agility: { footwork: 0.2, 'ball-control': 0.2, agility: 0.6 },
};
